# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dc15d73c1db759c92a02e755be2a7023a5b995936ecfd0d39df73b48c5ff9a72054b3752de02669df4ef4be2cb512579f36e83faddd68858ce3ec12ec026982

test:
  secret_key_base: 896980798316d0af6cc58040bf84ed83f841228d143384c8a9f9750544af576872fdddebef727e0a9752269139a3befcd5d29d4231b39656dce3cd942e4e8a00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
